services:
  app:
    image: ghcr.io/ashishbhatiya18/citrusdental-admin:main
    container_name: admin
    restart: always
    extra_hosts:
      - pg.ab18.in=10.10.10.11
    env_file: .env
    networks:
      - tailscale_bridge
    environment:
      - EMAIL_TOKEN_FILE=/app/secrets/email_token.json
    volumes:
      - /home/dietpi/localstack/secrets/email_token.json:/app/secrets/email_token.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.admin.rule=Host(`admin.citrusdental.in`)
      - homepage.group=CD Utilities
      - homepage.name=CitrusDental Admin
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/fastapi.png
      - homepage.description=Citrus Dental Admin Panel
networks:
  tailscale_bridge:
    external: true