services:
  cloudflared:
    command: tunnel --no-autoupdate run
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    networks:
      - tailscale_bridge
    environment:
      - TUNNEL_TOKEN_FILE=/run/secrets/cloudflare_tunnel_token
    labels:
      - homepage.group=CD Utilities
      - homepage.name=Cloudflare Tunnel
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/cloudflare-zero-trust.png
      - homepage.description=Cloudflare Tunnel
      - homepage.widget.type=cloudflared
    secrets:
      - cloudflare_tunnel_token
  citrusdental-bfe:
    image: ghcr.io/ashishbhatiya18/citrusdental-bfe:main
    container_name: citrusdental-bfe
    networks:
      - tailscale_bridge
    env_file: .env
    extra_hosts:
      - pg.ab18.in=10.10.10.11
    environment:
      - GOOGLE_TOKEN_FILE=/app/secrets/google_token.json
    volumes:
      - /home/dietpi/localstack/secrets/google_token.json:/app/secrets/google_token.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.bfe.rule=Host(`api.citrusdental.in`)
      - homepage.group=CD Utilities
      - homepage.name=CitrusDental API
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/fastapi.png
      - homepage.description=Citrus Dental API
networks:
  tailscale_bridge:
    external: true

secrets:
  cloudflare_tunnel_token:
    file: /home/dietpi/localstack/secrets/cloudflare_tunnel_token
