services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    restart: no
    volumes:
      - /home/dietpi/localstack/data/termix_data:/app/data
    networks:
      - network-layer
    labels:
      - traefik.enable=true
      - traefik.http.routers.term.rule=Host(`term.ab18.in`)
      - traefik.http.routers.term.middlewares=auth
      - homepage.group=Utilities
      - homepage.name=Termix
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/termix.png
      - homepage.href=https://term.ab18.in
      - homepage.description=Access Terminals Remotely
networks:
  network-layer:
    name: tailscale_bridge
    external: true