services:
  rustpad:
    image: ekzhang/rustpad
    container_name: rustpad
    restart: always
    networks:
      - network-layer
    labels:
      - traefik.enable=true
      - traefik.http.routers.pad.rule=Host(`pad.ab18.in`)
      - traefik.http.services.pad.loadbalancer.server.port=3030
      - traefik.http.routers.pad.service=pad
      - homepage.group=Utilities
      - homepage.name=RustPad
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/etherpad.png
      - homepage.href=https://pad.ab18.in
      - homepage.description=Online NotePad
    environment:
      - EXPIRY_DAYS=30
      - SQLITE_URI=/data/db.sqlite
      - RUST_LOG=info
    volumes:
      - /home/dietpi/localstack/data/rustpad_data:/data
networks:
  network-layer:
    name: tailscale_bridge
    external: true