services:
  isponsorblock:
    image: dmunozv04/isponsorblocktv
    container_name: isponsorblock
    volumes:
      - /home/dietpi/localstack/config/isponsorblock:/app/data
    restart: always
    labels:
      - homepage.group=Local Utilities
      - homepage.name=iSponsorBlock
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/youtube-tv.png
      - homepage.description=Controls YouTube Ads
    #network_mode: host