services:
  postgresql:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: postgres
    hostname: postgres
    restart: always
    volumes:
      - /home/dietpi/localstack/data/pg_data:/var/lib/postgresql/data
    environment:
      DB_USERNAME: immich
      DB_DATABASE_NAME: photos
      POSTGRES_INITDB_ARGS: --data-checksums
    env_file: .env
    networks:
      - data-layer
      - network-layer
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.pg.rule=HostSNI(`pg.ab18.in`)
      - traefik.tcp.routers.pg.tls.options=db@file
      - traefik.tcp.routers.pg.entrypoints=websecure
      - traefik.tcp.routers.pg.tls=true
    shm_size: 128mb
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - data-layer
      - network-layer
    volumes:
      - /home/dietpi/localstack/data/redis_data:/data
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.redis.rule=HostSNI(`redis.ab18.in`)
      - traefik.tcp.routers.redis.entrypoints=websecure
      - traefik.tcp.routers.redis.tls=true
  mysql:
    image: linuxserver/mariadb
    container_name: mysql
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Kolkata
    env_file: .env
    volumes:
      - /home/dietpi/localstack/data/mysql_data:/config
    networks:
      - data-layer
      - network-layer
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mysql.rule=HostSNI(`mysql.ab18.in`)
      - traefik.tcp.routers.mysql.entrypoints=websecure
      - traefik.tcp.routers.mysql.tls=true
networks:
  data-layer:
    external: true
  network-layer:
    name: tailscale_bridge
    external: true
