services:
  api:
    image: ghcr.io/ashishbhatiya18/costaebella-backend:latest
    container_name: costaebella-be
    restart: always
    env_file:
      - /home/dietpi/localstack/secrets/costaebella/env
    networks:
      - internal_bridge
      - native
    extra_hosts:
      - "pg.ab18.in:10.10.10.11"
  cloudflared:
    command: tunnel --no-autoupdate run
    image: cloudflare/cloudflared:latest
    container_name: costaebella-cloudflare
    restart: always
    networks:
      - internal_bridge
      - native
    environment:
      - TUNNEL_TOKEN_FILE=/run/secrets/cloudflare_tunnel_token
    secrets:
      - cloudflare_tunnel_token

networks:
  native: {}
  internal_bridge:
    external: true

secrets:
  cloudflare_tunnel_token:
    file: /home/dietpi/localstack/secrets/costaebella_cloudflare_tunnel_token