services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    networks:
      - network-layer
    restart: always
    volumes:
      - /home/dietpi/localstack/data/linkding_data:/etc/linkding/data
    environment:
      - LD_ENABLE_AUTH_PROXY=True
      - LD_AUTH_PROXY_USERNAME_HEADER=HTTP_X_AUTH_REQUEST_USER
    labels:
      - traefik.enable=true
      - traefik.http.routers.link.rule=Host(`bookmark.ab18.in`) && !PathPrefix(`/api`)
      - traefik.http.routers.link2.rule=Host(`bookmark.ab18.in`) && PathPrefix(`/api`)
      - traefik.http.routers.link.middlewares=auth
      - homepage.group=Utilities
      - homepage.name=LinkDing
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/linkding.png
      - homepage.href=https://bookmark.ab18.in
      - homepage.description=Save Your Bookmarks

networks:
  network-layer:
    name: tailscale_bridge
    external: true