services:
  stirlingpdf:
    image: stirlingtools/stirling-pdf:latest-ultra-lite
    container_name: stirlingpdf
    networks:
      - network-layer
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.pdf.rule=Host(`pdf.ab18.in`) || Host(`pdf`)
      - traefik.http.routers.pdf.middlewares=auth
      - homepage.group=Utilities
      - homepage.name=Stirling PDF
      - homepage.icon=https://cdn-icons-png.freepik.com/512/3997/3997635.png?fd=1&filename=pdf_3997635.png
      - homepage.href=https://pdf.ab18.in
      - homepage.description=PDF Utility
networks:
  network-layer:
    name: tailscale_bridge
    external: true