services:
  registry:
    image: registry:3
    container_name: registry
    restart: never
    networks:
      - network-layer
    labels:
      - traefik.enable=true
      - traefik.http.routers.hub.rule=Host(`hub.ab18.in`)
networks:
  network-layer:
    name: tailscale_bridge
    external: true
