services:
  api:
    image: ghcr.io/ashishbhatiya18/smile-design-backend:latest
    container_name: smiledesign-be
    platform: linux/arm64
    restart: always
    env_file:
      - /home/dietpi/localstack/secrets/smiledesign/env
    networks:
      - internal_bridge
    labels:
      - traefik.enable=true
      - traefik.http.routers.smiledesign-be.rule=Host(`smiledesign-be.citrusdental.in`)
      - traefik.http.routers.smiledesign-be.middlewares=smiledesign-be-ratelimit
      - traefik.http.middlewares.smiledesign-be-ratelimit.ratelimit.average=60
      - traefik.http.middlewares.smiledesign-be-ratelimit.ratelimit.burst=20
      - traefik.http.middlewares.smiledesign-be-ratelimit.ratelimit.period=1m
  cloudflared:
    command: tunnel --no-autoupdate run
    image: cloudflare/cloudflared:latest
    container_name: smiledesign-cloudflare
    restart: always
    networks:
      - internal_bridge
    environment:
      - TUNNEL_TOKEN_FILE=/run/secrets/smiledesign_cloudflare_tunnel_token
    secrets:
      - smiledesign_cloudflare_tunnel_token

networks:
  internal_bridge:
    external: true

secrets:
  smiledesign_cloudflare_tunnel_token:
    file: /home/dietpi/localstack/secrets/smiledesign_cloudflare_tunnel_token
