services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    volumes:
      - /home/dietpi/localstack/data/vaultwarden_data:/data
    networks:
      - network-layer
    environment:
      - TZ=Asia/Kolkata
      - DATABASE_URL=postgresql://ab18:ab18@pg.ab18.in:443/ab18
    extra_hosts:
      - pg.ab18.in: 10.10.10.11
    labels:
      - traefik.enable=true
      - traefik.http.routers.vault.rule=Host(`vault.ab18.in`)
      - homepage.group=Utilities
      - homepage.name=VaultWarden
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/bitwarden.png
      - homepage.href=https://vault.ab18.in
      - homepage.description=Store your secrets securely
      #- traefik.http.routers.vault.middlewares=auth
networks:
  network-layer:
    name: tailscale_bridge
    external: true
