services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    networks:
      - network-layer
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.tools.rule=Host(`tools.ab18.in`)
      - traefik.http.routers.tools.middlewares=auth
      - homepage.group=Utilities
      - homepage.name=IT Tools
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/it-tools-light.png
      - homepage.href=https://tools.ab18.in
      - homepage.description=IT Tools - For Regular Use
networks:
  network-layer:
    name: tailscale_bridge
    external: true